[tools]
# Downloads nightly release: https://github.com/SeismicSystems/seismic-foundry/releases
# Contains sforge, sanvil, scast, schisel — all added to PATH.
# Pin updated from samlaf's seismic repo. Run `mise install` to get latest.
sfoundry = "nightly-08913bcc240efcb17dcee38e60adfa482b4bcd44"

# Downloads ssolc release: https://github.com/SeismicSystems/seismic-solidity/releases
ssolc = { version = "2ebb36d", bin = "ssolc" }

# TypeScript runtime & package manager
bun = "1.3.9"

[tool_alias]
sfoundry = "github:SeismicSystems/seismic-foundry"
ssolc = "github:SeismicSystems/seismic-solidity"
