// BracketGroups contract ABI — generated by sforge.
// Source: contracts/out/BracketGroups.sol/BracketGroups.json
//
// DO NOT EDIT MANUALLY. Rebuild contracts with sforge and copy the abi field.

export const BracketGroupsAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_marchMadness",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "MAX_SLUG_LENGTH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SCORING_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "collectWinnings",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createGroup",
    "inputs": [
      {
        "name": "slug",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "displayName",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "entryFee",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createGroupWithPassword",
    "inputs": [
      {
        "name": "slug",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "displayName",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "entryFee",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "password",
        "type": "sbytes12",
        "internalType": "sbytes12"
      }
    ],
    "outputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "editEntryName",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getGroup",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BracketGroups.Group",
        "components": [
          {
            "name": "slug",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "displayName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "creator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "entryCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "entryFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hasPassword",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getGroupBySlug",
    "inputs": [
      {
        "name": "slug",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BracketGroups.Group",
        "components": [
          {
            "name": "slug",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "displayName",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "creator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "entryCount",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "entryFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "hasPassword",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getIsMember",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "addr",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMember",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "index",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct BracketGroups.Member",
        "components": [
          {
            "name": "addr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "score",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "isScored",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMemberScore",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "index",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMembers",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct BracketGroups.Member[]",
        "components": [
          {
            "name": "addr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "score",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "isScored",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hasCollectedWinnings",
    "inputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isMemberOf",
    "inputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "joinGroup",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "joinGroupWithPassword",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "password",
        "type": "sbytes12",
        "internalType": "sbytes12"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "leaveGroup",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "marchMadness",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IMarchMadness"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "nextGroupId",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "payouts",
    "inputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "winningScore",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "numWinners",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "numScored",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "scoreEntry",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "memberIndex",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "slugToGroupId",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "EntryScored",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "memberIndex",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "addr",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "score",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GroupCreated",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "slug",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "displayName",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "creator",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "hasPassword",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MemberJoined",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "addr",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MemberLeft",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "addr",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "WinningsCollected",
    "inputs": [
      {
        "name": "groupId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "addr",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyAMember",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyCollected",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyScored",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CannotJoinAfterDeadline",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CannotLeaveAfterDeadline",
    "inputs": []
  },
  {
    "type": "error",
    "name": "GroupDoesNotExist",
    "inputs": []
  },
  {
    "type": "error",
    "name": "GroupIsNotPasswordProtected",
    "inputs": []
  },
  {
    "type": "error",
    "name": "GroupNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "IncorrectEntryFee",
    "inputs": [
      {
        "name": "expected",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "actual",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "IndexOutOfBounds",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoBracketInMainContract",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoEntriesScored",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoEntryFee",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAMember",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAWinner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotScored",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PasswordRequired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RefundFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ResultsNotPosted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ScoringWindowClosed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ScoringWindowStillOpen",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SlugAlreadyTaken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SlugCannotBeEmpty",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SlugTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongPassword",
    "inputs": []
  }
] as const;
