// BracketGroups contract ABI — generated by ssolc.
// Source: contracts/src/BracketGroups.sol
//
// DO NOT EDIT MANUALLY. Run `bun run gen:abis` to regenerate.

export const BracketGroupsAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_marchMadness",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AlreadyAMember",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyCollected",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyScored",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CannotJoinAfterDeadline",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CannotLeaveAfterDeadline",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GroupDoesNotExist",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GroupIsNotPasswordProtected",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "GroupNotFound",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "expected",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "actual",
        "type": "uint256"
      }
    ],
    "name": "IncorrectEntryFee",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "IndexOutOfBounds",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoBracketInMainContract",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoEntriesScored",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoEntryFee",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotAMember",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotAWinner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotScored",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PasswordRequired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "RefundFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ResultsNotPosted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ScoringWindowClosed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ScoringWindowStillOpen",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SlugAlreadyTaken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SlugCannotBeEmpty",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SlugTooLong",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TransferFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "WrongPassword",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "memberIndex",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "addr",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "score",
        "type": "uint8"
      }
    ],
    "name": "EntryScored",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "slug",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "displayName",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "creator",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "hasPassword",
        "type": "bool"
      }
    ],
    "name": "GroupCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "addr",
        "type": "address"
      }
    ],
    "name": "MemberJoined",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "addr",
        "type": "address"
      }
    ],
    "name": "MemberLeft",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "addr",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "WinningsCollected",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MAX_SLUG_LENGTH",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "SCORING_DURATION",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      }
    ],
    "name": "collectWinnings",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "slug",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "displayName",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "entryFee",
        "type": "uint256"
      }
    ],
    "name": "createGroup",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "slug",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "displayName",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "entryFee",
        "type": "uint256"
      },
      {
        "internalType": "sbytes12",
        "name": "password",
        "type": "sbytes12"
      }
    ],
    "name": "createGroupWithPassword",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      }
    ],
    "name": "editEntryName",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      }
    ],
    "name": "getGroup",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "slug",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "displayName",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "creator",
            "type": "address"
          },
          {
            "internalType": "uint32",
            "name": "entryCount",
            "type": "uint32"
          },
          {
            "internalType": "uint256",
            "name": "entryFee",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "hasPassword",
            "type": "bool"
          }
        ],
        "internalType": "struct BracketGroups.Group",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "slug",
        "type": "string"
      }
    ],
    "name": "getGroupBySlug",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      },
      {
        "components": [
          {
            "internalType": "string",
            "name": "slug",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "displayName",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "creator",
            "type": "address"
          },
          {
            "internalType": "uint32",
            "name": "entryCount",
            "type": "uint32"
          },
          {
            "internalType": "uint256",
            "name": "entryFee",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "hasPassword",
            "type": "bool"
          }
        ],
        "internalType": "struct BracketGroups.Group",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "internalType": "address",
        "name": "addr",
        "type": "address"
      }
    ],
    "name": "getIsMember",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "index",
        "type": "uint32"
      }
    ],
    "name": "getMember",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "addr",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "uint8",
            "name": "score",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "isScored",
            "type": "bool"
          }
        ],
        "internalType": "struct BracketGroups.Member",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "index",
        "type": "uint32"
      }
    ],
    "name": "getMemberScore",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      }
    ],
    "name": "getMembers",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "addr",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "uint8",
            "name": "score",
            "type": "uint8"
          },
          {
            "internalType": "bool",
            "name": "isScored",
            "type": "bool"
          }
        ],
        "internalType": "struct BracketGroups.Member[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "hasCollectedWinnings",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "isMemberOf",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      }
    ],
    "name": "joinGroup",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "internalType": "sbytes12",
        "name": "password",
        "type": "sbytes12"
      },
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      }
    ],
    "name": "joinGroupWithPassword",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      }
    ],
    "name": "leaveGroup",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "marchMadness",
    "outputs": [
      {
        "internalType": "contract IMarchMadness",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "nextGroupId",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "name": "payouts",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "winningScore",
        "type": "uint8"
      },
      {
        "internalType": "uint32",
        "name": "numWinners",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "numScored",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "groupId",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "memberIndex",
        "type": "uint32"
      }
    ],
    "name": "scoreEntry",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "slugToGroupId",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
