// BracketMirror contract ABI — generated by ssolc.
// Source: contracts/src/BracketMirror.sol
//
// DO NOT EDIT MANUALLY. Run `bun run gen:abis` to regenerate.

export const BracketMirrorAbi = [
  {
    "inputs": [],
    "name": "EntryNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EntrySlugAlreadyTaken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "IndexOutOfBounds",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSentinelByte",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MirrorDoesNotExist",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MirrorNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotMirrorAdmin",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SlugAlreadyTaken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SlugCannotBeEmpty",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SlugTooLong",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "slug",
        "type": "string"
      }
    ],
    "name": "BracketUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "slug",
        "type": "string"
      }
    ],
    "name": "EntryAdded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "slug",
        "type": "string"
      }
    ],
    "name": "EntryRemoved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "slug",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "displayName",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "admin",
        "type": "address"
      }
    ],
    "name": "MirrorCreated",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "MAX_SLUG_LENGTH",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "internalType": "bytes8",
        "name": "bracket",
        "type": "bytes8"
      },
      {
        "internalType": "string",
        "name": "slug",
        "type": "string"
      }
    ],
    "name": "addEntry",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "slug",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "displayName",
        "type": "string"
      }
    ],
    "name": "createMirror",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      }
    ],
    "name": "getEntries",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes8",
            "name": "bracket",
            "type": "bytes8"
          },
          {
            "internalType": "string",
            "name": "slug",
            "type": "string"
          }
        ],
        "internalType": "struct BracketMirror.MirrorEntry[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "index",
        "type": "uint256"
      }
    ],
    "name": "getEntry",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes8",
            "name": "bracket",
            "type": "bytes8"
          },
          {
            "internalType": "string",
            "name": "slug",
            "type": "string"
          }
        ],
        "internalType": "struct BracketMirror.MirrorEntry",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "slug",
        "type": "string"
      }
    ],
    "name": "getEntryBySlug",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes8",
            "name": "bracket",
            "type": "bytes8"
          },
          {
            "internalType": "string",
            "name": "slug",
            "type": "string"
          }
        ],
        "internalType": "struct BracketMirror.MirrorEntry",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      }
    ],
    "name": "getEntryCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      }
    ],
    "name": "getMirror",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "slug",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "displayName",
            "type": "string"
          },
          {
            "internalType": "uint32",
            "name": "entryFee",
            "type": "uint32"
          },
          {
            "internalType": "string",
            "name": "entryCurrency",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "admin",
            "type": "address"
          }
        ],
        "internalType": "struct BracketMirror.Mirror",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "slug",
        "type": "string"
      }
    ],
    "name": "getMirrorBySlug",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "nextMirrorId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      }
    ],
    "name": "removeEntry",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "internalType": "uint32",
        "name": "fee",
        "type": "uint32"
      },
      {
        "internalType": "string",
        "name": "currency",
        "type": "string"
      }
    ],
    "name": "setEntryFee",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "slugToMirrorId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      },
      {
        "internalType": "bytes8",
        "name": "bracket",
        "type": "bytes8"
      }
    ],
    "name": "updateBracket",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "mirrorId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "entryIndex",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "slug",
        "type": "string"
      }
    ],
    "name": "updateEntrySlug",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;
