/** MarchMadness contract ABI — only the functions we call from the frontend */
export const marchMadnessAbi = [
  {
    type: "function",
    name: "submitBracket",
    inputs: [{ name: "bracket", type: "bytes8" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "updateBracket",
    inputs: [{ name: "bracket", type: "bytes8" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTag",
    inputs: [{ name: "tag", type: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getBracket",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bytes8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEntryCount",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTag",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getScore",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIsScored",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "submissionDeadline",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entryFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "results",
    inputs: [],
    outputs: [{ name: "", type: "bytes8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "winningScore",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "numEntries",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "scoreBracket",
    inputs: [{ name: "account", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "collectWinnings",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "BracketSubmitted",
    inputs: [{ name: "account", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "TagSet",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "tag", type: "string", indexed: false },
    ],
  },
] as const;
