[program:server]
command=/home/ubuntu/march-madness/target/release/march-madness-server
directory=/home/ubuntu/march-madness
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/server.err.log
stdout_logfile=/var/log/supervisor/server.out.log

[program:indexer]
command=/home/ubuntu/march-madness/target/release/march-madness-indexer listen
directory=/home/ubuntu/march-madness
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/indexer.err.log
stdout_logfile=/var/log/supervisor/indexer.out.log

[program:forecaster]
command=/home/ubuntu/march-madness/target/release/march-madness-forecaster
directory=/home/ubuntu/march-madness
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/forecaster.err.log
stdout_logfile=/var/log/supervisor/forecaster.out.log

[program:ncaa-feed]
command=/home/ubuntu/march-madness/target/release/ncaa-feed
    --output-file /home/ubuntu/march-madness/data/2026/men/status.json
directory=/home/ubuntu/march-madness
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/ncaa-feed.err.log
stdout_logfile=/var/log/supervisor/ncaa-feed.out.log
