[program:mm-server]
command=/home/ubuntu/march-madness/target/release/server
    --tournament-status-file /home/ubuntu/march-madness/data/2026/men/status.json
    --forecasts-file /home/ubuntu/march-madness/data/2026/men/forecasts.json
directory=/home/ubuntu/march-madness
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/mm-server.err.log
stdout_logfile=/var/log/supervisor/mm-server.out.log
environment=REDIS_URL="redis://127.0.0.1:6379",RUST_LOG="info"

[program:mm-indexer]
command=/home/ubuntu/march-madness/target/release/indexer listen
directory=/home/ubuntu/march-madness
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/mm-indexer.err.log
stdout_logfile=/var/log/supervisor/mm-indexer.out.log
environment=REDIS_URL="redis://127.0.0.1:6379",VITE_RPC_URL="%(ENV_VITE_RPC_URL)s",RUST_LOG="info"

[program:mm-ncaa-feed]
command=/home/ubuntu/march-madness/target/release/ncaa-feed
    --output-file /home/ubuntu/march-madness/data/2026/men/status.json
directory=/home/ubuntu/march-madness
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/mm-ncaa-feed.err.log
stdout_logfile=/var/log/supervisor/mm-ncaa-feed.out.log
environment=RUST_LOG="info"
