import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

type ContractAbiTarget = {
  source: string;
  contractName: string;
  outputFile: string;
  banner: string;
};

const REPO_ROOT = resolve(import.meta.dir, "..");
const CONTRACTS_DIR = resolve(REPO_ROOT, "contracts");

const TARGETS: ContractAbiTarget[] = [
  {
    source: "src/MarchMadness.sol",
    contractName: "MarchMadness",
    outputFile: resolve(REPO_ROOT, "packages/client/src/abi.ts"),
    banner: "MarchMadness contract ABI",
  },
  {
    source: "src/BracketGroups.sol",
    contractName: "BracketGroups",
    outputFile: resolve(REPO_ROOT, "packages/client/src/abi-groups.ts"),
    banner: "BracketGroups contract ABI",
  },
  {
    source: "src/BracketMirror.sol",
    contractName: "BracketMirror",
    outputFile: resolve(REPO_ROOT, "packages/client/src/abi-mirror.ts"),
    banner: "BracketMirror contract ABI",
  },
];

function findSsolc(): string {
  const configured = process.env.FOUNDRY_SOLC;
  if (configured) return configured;
  return execFileSync("mise", ["which", "ssolc"], {
    cwd: REPO_ROOT,
    encoding: "utf8",
  }).trim();
}

function extractJson(output: string): Record<string, unknown> {
  const start = output.indexOf("{");
  if (start === -1) {
    throw new Error(`Failed to parse ssolc output as JSON:\n${output}`);
  }
  return JSON.parse(output.slice(start)) as Record<string, unknown>;
}

function generateAbiFile(target: ContractAbiTarget, abi: unknown): string {
  return `// ${target.banner} — generated by ssolc.\n` +
    `// Source: contracts/${target.source}\n` +
    `//\n` +
    `// DO NOT EDIT MANUALLY. Run \`bun run gen:abis\` to regenerate.\n\n` +
    `export const ${target.contractName}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

const ssolc = findSsolc();
const sources = TARGETS.map((target) => target.source);
const raw = execFileSync(
  ssolc,
  ["--combined-json", "abi", "--base-path", ".", "--include-path", "lib", ...sources],
  {
    cwd: CONTRACTS_DIR,
    encoding: "utf8",
  },
);

const output = extractJson(raw);
const contracts = output.contracts as Record<string, { abi: unknown }>;

for (const target of TARGETS) {
  const key = `${target.source}:${target.contractName}`;
  const contract = contracts[key];
  if (!contract) {
    throw new Error(`Missing ABI for ${key}`);
  }

  mkdirSync(dirname(target.outputFile), { recursive: true });
  writeFileSync(target.outputFile, generateAbiFile(target, contract.abi));
  console.log(`wrote ${target.outputFile}`);
}
